# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: "(chore)"

  # Maintain dependencies for npm
  # - package-ecosystem: "npm"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   groups:
  #     npm:
  #       patterns:
  #         - "*"
  #   commit-message:
  #     prefix: "(chore)"
  #   versioning-strategy: lockfile-only

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      composer:
        patterns:
          - "*"
    commit-message:
      prefix: "(chore)"
    versioning-strategy: lockfile-only
