name: Create Badges

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-badges:
    uses: yardinternet/workflows/.github/workflows/badges.yml@main
    secrets: inherit
