name: 'Labeler'

on:
    pull_request:
        types: [opened]

jobs:
    label:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write

        steps:
            - uses: actions/checkout@v4

            - name: Labeler
              uses: actions/labeler@v5.0.0
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
