name: linting
on:
  pull_request:
    paths:
        - '**.md'

jobs:
  lint:
    name: Markdown Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          globs: |
            *.md
          config: .markdownlint.yml
