name: NPM Lockfile Changes
on:
  pull_request:
    paths:
      - 'package-lock.json'

jobs:
  php-cs-fixer:
    uses: yardinternet/workflows/.github/workflows/npm-lock-diff.yml@main
    secrets: inherit
