name: PHPStan

on:
    pull_request:
        paths:
            - '**.php'
            - 'phpstan.neon.dist'
            - '.github/workflows/phpstan.yml'

jobs:
  phpstan:
    uses: yardinternet/workflows/.github/workflows/phpstan.yml@main
    secrets: inherit
