name: Tests

on:
  pull_request:
    paths:
      - '**.php'
      - '.github/workflows/run-tests.yml'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'composer.lock'
  workflow_dispatch:

jobs:
  test:
    uses: yardinternet/workflows/.github/workflows/run-laravel-testbench-tests.yml@main
    secrets: inherit
